"""Dispatch Table

Revision ID: 0d21810a757f
Revises: 7542f5554b6a
Create Date: 2023-08-17 22:22:19.170197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d21810a757f'
down_revision = '7542f5554b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch',
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('dispatch_id')
    )
    op.create_table('dispatch_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch.dispatch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_details')
    op.drop_table('dispatch')
    # ### end Alembic commands ###
