"""Unit cost in Ingredients

Revision ID: 500ff655890e
Revises: 92bb5860b239
Create Date: 2023-08-21 13:32:55.964540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500ff655890e'
down_revision = '92bb5860b239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.Float(), nullable=False))

    with op.batch_alter_table('supplier_ingredients', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.FLOAT(), nullable=False))

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')

    # ### end Alembic commands ###
