"""production run flour

Revision ID: 6059cfcfd8f0
Revises: c6fe8484bf51
Create Date: 2023-03-27 09:17:55.765618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6059cfcfd8f0'
down_revision = 'c6fe8484bf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flour_kneaded', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_runs', schema=None) as batch_op:
        batch_op.drop_column('flour_kneaded')

    # ### end Alembic commands ###
