"""New sales tables

Revision ID: 626a4a0ed09b
Revises: 7beb03934faa
Create Date: 2023-06-19 21:58:50.139516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626a4a0ed09b'
down_revision = '7beb03934faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('sales_associate_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('sales_associate_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('returns')
    op.drop_table('dispatch')
    # ### end Alembic commands ###
