"""Allow users to change details about them

Revision ID: 640f09a8c5b8
Revises: dc3df7bb2af9
Create Date: 2023-03-14 21:14:01.371038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640f09a8c5b8'
down_revision = 'dc3df7bb2af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('member_since', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('member_since')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
