"""relationship btw customer and route

Revision ID: 7542f5554b6a
Revises: 8fa1cde0cfd6
Create Date: 2023-08-16 12:52:21.835245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7542f5554b6a'
down_revision = '8fa1cde0cfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('route_id', 'routes', ['route_id'], ['route_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
