"""Sales tables

Revision ID: 7beb03934faa
Revises: 51e7de0555da
Create Date: 2023-06-19 19:07:11.448037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7beb03934faa'
down_revision = '51e7de0555da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone_no', sa.Integer(), nullable=True),
    sa.Column('mpesa_agent_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=28), nullable=True),
    sa.Column('details', sa.String(length=56), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saleDate', sa.DateTime(), nullable=True),
    sa.Column('totalAmount', sa.Float(), nullable=True),
    sa.Column('paymentMethod', sa.String(length=28), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('report_type', sa.String(length=28), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('top_selling_products', sa.String(length=56), nullable=True),
    sa.Column('customer_sales_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_reports')
    op.drop_table('sales')
    op.drop_table('payment_methods')
    op.drop_table('orders')
    op.drop_table('orderdetails')
    op.drop_table('customers')
    # ### end Alembic commands ###
