"""Order, OrderDetails and PaymentMethods

Revision ID: 97d98efa06f3
Revises: 0d21810a757f
Create Date: 2023-08-20 11:49:41.237429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d98efa06f3'
down_revision = '0d21810a757f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=28), nullable=True),
    sa.Column('method_details', sa.String(length=56), nullable=True),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.cust_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.method_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_details',
    sa.Column('order_detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('orders')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
