"""another migration

Revision ID: dc3df7bb2af9
Revises: 18658654d370
Create Date: 2023-03-08 16:45:34.413381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3df7bb2af9'
down_revision = '18658654d370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
